name: Build Dockerfile

on:
  workflow_dispatch:

jobs:
  build-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build Dockerfile
        shell: bash
        run: |
          docker build .
